#!/usr/bin/env python3
"""Build a tiny FAT12 disk image (one file) and emit it as a PROGMEM C array
for the Digispark V-USB MSC firmware (Stage 1 test)."""

SECTOR = 512
SECTORS_PER_CLUSTER = 1
RESERVED_SECTORS = 1
NUM_FATS = 1  # non-standard but tolerated by Linux/most drivers; saves flash
ROOT_ENTRIES = 16
DATA_CLUSTERS = 1  # ATtiny85 has only 8KB flash total - keep the embedded disk tiny

FAT_SECTORS = 1  # plenty for 20 clusters (12-bit entries fit easily in 512 bytes)
ROOTDIR_SECTORS = (ROOT_ENTRIES * 32) // SECTOR  # = 1
TOTAL_SECTORS = RESERVED_SECTORS + NUM_FATS * FAT_SECTORS + ROOTDIR_SECTORS + DATA_CLUSTERS

FIRST_DATA_LBA = RESERVED_SECTORS + NUM_FATS * FAT_SECTORS + ROOTDIR_SECTORS

FILE_CONTENT = (
    b"This file is being served live by a Digispark (ATtiny85 + V-USB)\r\n"
    b"pretending to be a USB flash drive over Bulk-Only Transport / SCSI.\r\n"
    b"If you can read this on the host, Stage 1 of the car-radio project\r\n"
    b"(fake USB MSC device) is working.\r\n"
)
FILE_NAME = "README  TXT"  # 8.3, space-padded: "README" + "TXT"


def pack_fat12(entries):
    """entries: list of 12-bit ints. Returns packed bytes."""
    out = bytearray()
    i = 0
    while i < len(entries):
        e0 = entries[i]
        e1 = entries[i + 1] if i + 1 < len(entries) else 0
        out.append(e0 & 0xFF)
        out.append(((e0 >> 8) & 0x0F) | ((e1 & 0x0F) << 4))
        out.append((e1 >> 4) & 0xFF)
        i += 2
    return bytes(out)


def build_boot_sector():
    bs = bytearray(SECTOR)
    bs[0:3] = b"\xEB\x3C\x90"
    bs[3:11] = b"MSCFAKE1"
    bs[11:13] = SECTOR.to_bytes(2, "little")
    bs[13] = SECTORS_PER_CLUSTER
    bs[14:16] = RESERVED_SECTORS.to_bytes(2, "little")
    bs[16] = NUM_FATS
    bs[17:19] = ROOT_ENTRIES.to_bytes(2, "little")
    bs[19:21] = TOTAL_SECTORS.to_bytes(2, "little")
    bs[21] = 0xF8  # media descriptor (fixed/non-removable-style, common for USB disks)
    bs[22:24] = FAT_SECTORS.to_bytes(2, "little")
    bs[24:26] = (32).to_bytes(2, "little")  # sectors per track (legacy, unused)
    bs[26:28] = (64).to_bytes(2, "little")  # heads (legacy, unused)
    bs[28:32] = (0).to_bytes(4, "little")  # hidden sectors
    bs[32:36] = (0).to_bytes(4, "little")  # total sectors (32-bit, unused, we use 16-bit field)
    bs[36] = 0x80  # drive number
    bs[37] = 0  # reserved
    bs[38] = 0x29  # boot signature
    bs[39:43] = (0x12345678).to_bytes(4, "little")  # volume ID
    bs[43:54] = b"MSC FAKE   "  # volume label, 11 bytes
    bs[54:62] = b"FAT12   "  # filesystem type, 8 bytes
    bs[510] = 0x55
    bs[511] = 0xAA
    return bytes(bs)


def build_fat_sector():
    entries = [0] * (DATA_CLUSTERS + 2)
    entries[0] = 0xFF8  # reserved, media descriptor byte pattern
    entries[1] = 0xFFF  # reserved
    entries[2] = 0xFFF  # our file's single cluster: end-of-chain
    packed = pack_fat12(entries)
    sector = bytearray(SECTOR)
    sector[: len(packed)] = packed
    return bytes(sector)


def build_root_dir_sector():
    sector = bytearray(SECTOR)
    entry = bytearray(32)
    entry[0:11] = FILE_NAME.encode("ascii")
    entry[11] = 0x20  # ARCHIVE attribute
    entry[12] = 0  # reserved
    entry[13] = 0  # creation time, tenths
    entry[14:16] = (0).to_bytes(2, "little")  # creation time
    entry[16:18] = (0x4A21).to_bytes(2, "little")  # creation date (arbitrary valid date)
    entry[18:20] = (0x4A21).to_bytes(2, "little")  # last access date
    entry[20:22] = (0).to_bytes(2, "little")  # first cluster high (0 for FAT12)
    entry[22:24] = (0).to_bytes(2, "little")  # write time
    entry[24:26] = (0x4A21).to_bytes(2, "little")  # write date
    entry[26:28] = (2).to_bytes(2, "little")  # first cluster low = 2
    entry[28:32] = len(FILE_CONTENT).to_bytes(4, "little")  # file size
    sector[0:32] = entry
    return bytes(sector)


def build_data_area():
    data = bytearray(DATA_CLUSTERS * SECTOR)
    data[: len(FILE_CONTENT)] = FILE_CONTENT
    return bytes(data)


def main():
    image = bytearray()
    image += build_boot_sector()
    for _ in range(NUM_FATS):
        image += build_fat_sector()
    image += build_root_dir_sector()
    image += build_data_area()

    assert len(image) == TOTAL_SECTORS * SECTOR, (len(image), TOTAL_SECTORS * SECTOR)

    with open("firmware/disk_image.h", "w") as f:
        f.write("/* auto-generated by gen_fat_image.py - do not edit by hand */\n")
        f.write("#ifndef DISK_IMAGE_H\n#define DISK_IMAGE_H\n\n")
        f.write("#include <avr/pgmspace.h>\n\n")
        f.write(f"#define DISK_TOTAL_SECTORS {TOTAL_SECTORS}\n")
        f.write(f"#define DISK_SECTOR_SIZE {SECTOR}\n\n")
        f.write("static const uint8_t disk_image[] PROGMEM = {\n")
        for i in range(0, len(image), 16):
            row = ", ".join(f"0x{b:02X}" for b in image[i : i + 16])
            f.write(f"    {row},\n")
        f.write("};\n\n#endif\n")

    print(f"Wrote firmware/disk_image.h: {TOTAL_SECTORS} sectors, {len(image)} bytes total, "
          f"data starts at LBA {FIRST_DATA_LBA}")


if __name__ == "__main__":
    main()
